apiVersion: v1
kind: Service
metadata:
  name: {{ include "smtp-cloud-relay.fullname" . }}
  labels:
    {{- include "smtp-cloud-relay.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "smtp-cloud-relay.selectorLabels" . | nindent 4 }}
  ports:
    - name: smtp
      port: {{ .Values.smtp.port }}
      targetPort: smtp
      protocol: TCP
    {{- if .Values.smtp.smtps.enabled }}
    - name: smtps
      port: {{ .Values.smtp.smtps.port }}
      targetPort: smtps
      protocol: TCP
    {{- end }}
    - name: http
      port: {{ .Values.http.port }}
      targetPort: http
      protocol: TCP
